apiVersion: kustomize.toolkit.fluxcd.io/v1beta1 
kind: Kustomization 
metadata:   
  name: my-app   
  namespace: flux-system 
spec:   
  interval: 10m   
  path: "./deploy"   
  prune: true   
  sourceRef:     
    kind: GitRepository     
    name: my-repository   
    targetNamespace: default